language:
  java
jdk:
  - oraclejdk8
sudo: required
dist: trusty

addons:
  firefox: "49.0"
  code_climate:
      repo_token: CODE_CLIMATE_TOKEN

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo apt install libappindicator1 libdbusmenu-glib4 libdbusmenu-gtk4 libindicator7 libpango1.0-0 libpangox-1.0-0
 - sudo dpkg -i google-chrome-stable_current_amd64.deb
 - sudo apt update
 - sudo apt upgrade

script:
  mvn clean verify test